# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolelist',
            name='Permission',
            field=models.ManyToManyField(blank=True, to='face.PermissionList'),
        ),
    ]
